branch-defaults:
  default:
    environment: crm-api-demo
    group_suffix: null
global:
  application_name: crm-api-demo
  branch: null
  default_ec2_keyname: vockey
  default_platform: Python 3.12
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
